name: Withdraw from Funding Circle

on:
  schedule: 
    - cron: "0 19 * * 1"


jobs:
  build:
    runs-on: ubunut-latest
    steps:
      - name: NPM install
        run: |
          npm install
        
      - name: run it
        run: |
          npm run test -- --spec=cypress/e2e/funding-circle/withdraw.cy.js
